
# Copyright Red Hat

apiVersion: v1
kind: Service
metadata:
  name: compute-operator-webhook-service
  namespace: {{ .Namespace }}
  annotations:
    "service.beta.openshift.io/serving-cert-secret-name": compute-operator-webhook-service
spec:
  ports:
    - port: 443
      targetPort: 6443
  selector:
    control-plane: compute-operator-webhook-service
