# Copyright Red Hat

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-registration-operator-leader-election-rolebinding
  namespace: {{ .Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-operator-role
subjects:
- kind: ServiceAccount
  name: cluster-registration-operator-manager
  namespace: cluster-registation-config
